# In .base.yaml
wifi:
  networks:
  - ssid: 'iotwifinetwork'
    password: !secret <iotwifinetwork>_password
  - ssid: 'wifinetwork'
    password: !secret <wifinetwork>_password
  domain: '<something>.com'

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "esphome1"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80

#Text sensor
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${devicename} IP Address
